"""
Django settings for Qshop project.

Generated by 'django-admin startproject' using Django 2.1.8.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'oxcrhjp&+lj=e^#tk$ckwor0dqs86s6@_v&)0e1f^7rf5^%g+b'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Buyer',
    'Seller',
    'djcelery'
]

MIDDLEWARE = [
    'django.middleware.cache.UpdateCacheMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'Qshop.middleware.MiddleWareTest',
    'django.middleware.cache.FetchFromCacheMiddleware'
]

ROOT_URLCONF = 'Qshop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Qshop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS=(
    os.path.join(BASE_DIR,'static'),
)


#
# STATIC_ROOT=os.path.join(BASE_DIR,'static')




MEDIA_URL='/media/'
MEDIA_ROOT=os.path.join(BASE_DIR,'static')


# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
#     }
# }
# CACHE_MIDDLEWARE_KEY_PREFIX = ''
# CACHE_MIDDLEWARE_SECONDS = 600
# CACHE_MIDDLEWARE_ALIAS = 'default'

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION':[
            "127.0.0.1:11211"       #本地的memcache地址端口
        ]
    }
}
CACHE_MIDDLEWARE_KEY_PREFIX = ''
CACHE_MIDDLEWARE_SECONDS = 600
CACHE_MIDDLEWARE_ALIAS = 'default'





alipay_public_key_string = """-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqRsoGH+s/HJkAauRAvbAg9I5k7k9cl/AS84tz4h2OmbiTCSC7+wQzi6zC80zFrtLI6ULuxxJJ8oh28wewvsvcaqs9JcWShT0MgrtqAvXPuJ1TquRw9memOD4qT7uZBxrpra/bNu3LBjwIenkX3S2KyPW5KMHAy6qVObsqZdC6eOJkeqdPmsXsnxalYbOjnEtWIEWPDpMLThhMv/HeXp9SiszHFwS6McDgdbUZQIcbKDM63k2GKq8Q7m+TkozHiTlwEvzaiOas6+yTx8dLkfA+5ULTSgvabZ/bVTPpnaqkVcfiQFQmWrNWenqfdORAw3ApyaNs5XLCipPZXockJdCEQIDAQAB
-----END PUBLIC KEY-----"""

alipay_private_key_string = """-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEAqRsoGH+s/HJkAauRAvbAg9I5k7k9cl/AS84tz4h2OmbiTCSC7+wQzi6zC80zFrtLI6ULuxxJJ8oh28wewvsvcaqs9JcWShT0MgrtqAvXPuJ1TquRw9memOD4qT7uZBxrpra/bNu3LBjwIenkX3S2KyPW5KMHAy6qVObsqZdC6eOJkeqdPmsXsnxalYbOjnEtWIEWPDpMLThhMv/HeXp9SiszHFwS6McDgdbUZQIcbKDM63k2GKq8Q7m+TkozHiTlwEvzaiOas6+yTx8dLkfA+5ULTSgvabZ/bVTPpnaqkVcfiQFQmWrNWenqfdORAw3ApyaNs5XLCipPZXockJdCEQIDAQABAoIBAGkYoZCoOMAj75dCIztuUzMZwgLXCyM78uyp1Lq4GpItQtMDlgS596/MQiZBf1DPUeFzP5kn+ScrbmOFtlCDf3brFdZk18tuvl0jgZQA1+MTJsifxFWtt+1XU/MLU2kQaK8RwGJNIsfbL9JD5FSW2mhxO6qYz1Dg/acKZWb4xPNKHArV6FS3AkTNs+dXt70WOmqV3HKrL7B8F3NULV4/CAbbAWXspH7mw47v8sCyJTQm/QWA5EQ9/gLmZMkHxyBmyfRnfga0SrD2YWXIfGtexl1HQsx9oHtddCZQ0ncPurOW+Hcy5Wby23afe8iU3zB08cgANIbn2RyxVAW3Sdpe06kCgYEA6IiaYDN4OiT3/C/JIDAH4gGEEgKg5P9HpvF5ew+vmsWucWRQKehm9NokQ+D0hPDaCeJWrd23NisysP56occmylbajRGj+mQtlqAQdwXpjjkYGkpbUHHlmfyZVi/dvSEM+pWPg5YhcOlQB6+kFbTV1HlcLlNBAi0pNBwAUe+aqE8CgYEAuivu4m4Y2Ppw/jaahueYJeMMTvQslvzKbOZz+pBBiXFsgFiV0cYdfjvFAexyOEwR4FWqSIpiF9Vl58Rcm9XK6ttWAXpjCCxniBqmTKGA0cCN9idj/QsP3Yjv6f7zBbqybfjxH+EOI3K0/4dfCaJKKTc38nH3IjYtY2XdTZD0d58CgYEAqLW7s8KEH0OFPM560USn430QEnUfwSXKGcCnT/bghJ2aZCDQ3KcGU+4VU75aCj4pI/S4yOrNK5sJ60qnNMsmRLXhWWqMG3YlcVxutbxvaMXZy/FY8TPBzwhrRBH0gm0BWqm6d1EssBxG+Vyg4zLR1Ze7nsy+pNKZS3ppbQk3n5cCgYB+dbtF+a1NLgk01RhwTL6v9aN1uizTvxEtmfjsGbM6zl36bLIQFXgROD5hSSBpF1sJPId30PBC6kTXgy24+SdmEulABcdhVPBapmeSJB5h3F9R9n3X8/yp6gu1seWYXbI4O2Jm2jQFZjSGYoju/VtM1eJeAIXzqkN4gkgqGS3GVwKBgAS61CykNpRwRlc1BK6IhyvPQJLBLbV9Wath/WJFxfRUDtr6EgaEszEIRLVi7tlEgVyKLr0JOSYuYVa2qEui8AldpVhLTPvOIEscU2zSeI2MRrr814GI8DnA95V4iF6tMaMxnpL+vGZQyPpt/UPRwOHLt49/x72VochUY4gxp7/D
-----END RSA PRIVATE KEY-----"""

DING_URL="https://oapi.dingtalk.com/robot/send?access_token=be4b677556aef1f1c532ead9e3b18db2e6c3401f6f268cf53e7a59271bd85f74"

IPHON_URL="http://106.ihuyi.com/webservice/sms.php?method=Submit"

import djcelery
djcelery.setup_loader()
BROKER_URL='redis://127.0.0.1:6379/1'
CELERY_IMPORTS=('CeleryTask.tasks')
CELERY_TIMEZONE='Asia/Shanghai'
CELERYBEAT_SCHEDULER='djcelery.schedulers.DatabaseScheduler'

from celery.schedules import crontab
from celery.schedules import timedelta
CELERYBEAT_SCHEDULE={
    u'测试任务1':{
        "task":"CeleryTask.tasks.sendDing",
        "schedule":timedelta(seconds=5)
    }
}

ERROR_PATH=os.path.join(BASE_DIR,"error.log")

LOGGING={
    'version':1,
    'disable_existing_logger':False,
    'handlers':{
        "file":{
        "level":'DEBUG',
        "class":'logging.FileHandler',
        "filename":os.path.join(BASE_DIR,"django.log")

        }
    },
    'loggers':{
        'django':{
            'handlers':['file'],
            'level':'DEBUG',
            'propagate':True
        }
    }
}


