# Generated by Django 2.1.8 on 2019-09-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0013_auto_20190910_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_description',
            field=models.TextField(default='三娃超市,超市三娃'),
        ),
    ]
